# Generated by Django 4.2.2 on 2023-07-12 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('is_ordered', models.BooleanField(default=False)),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='The_Antiquarians_app.buyer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('year', models.IntegerField()),
                ('category', models.CharField(choices=[('Mebel', 'Mebel'), ('Nakit', 'Nakit'), ('Chasovnici', 'Chasovnici'), ('Kujnski pribor', 'Kujnski pribor'), ('Dekorativni raboti', 'Dekorativni raboti'), ('Interior', 'Interior'), ('Muzichki instrumenti', 'Muzichki instrumenti'), ('Igrachki', 'Igrachki'), ('Tekstil', 'Tekstil')], max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='The_Antiquarians_app/static/images/images')),
                ('description', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='The_Antiquarians_app.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='The_Antiquarians_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
                ('postal_code', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
                ('card_payment', models.BooleanField(default=False)),
                ('card_name_surname', models.CharField(max_length=100)),
                ('card_number', models.IntegerField()),
                ('card_valid_until', models.CharField(max_length=5)),
                ('card_ccv', models.IntegerField()),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='The_Antiquarians_app.buyer')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='The_Antiquarians_app.order')),
            ],
        ),
    ]
