# Generated by Django 4.2.2 on 2023-07-14 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('The_Antiquarians_app', '0003_remove_buyer_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_id',
        ),
    ]
