# Generated by Django 4.2.2 on 2023-07-14 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('The_Antiquarians_app', '0004_remove_order_order_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
