# Generated by Django 4.2.2 on 2023-07-14 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('The_Antiquarians_app', '0005_delete_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='posted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='The_Antiquarians_app.buyer'),
        ),
    ]
