# Generated by Django 4.2.2 on 2023-07-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('The_Antiquarians_app', '0006_product_posted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='password',
        ),
        migrations.RemoveField(
            model_name='product',
            name='posted_by',
        ),
        migrations.AddField(
            model_name='product',
            name='seller_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='seller_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='seller_name_and_surname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='seller_phone_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
