# Generated by Django 4.2.2 on 2023-07-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('The_Antiquarians_app', '0008_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Мебел', 'Мебел'), ('Накит', 'Накит'), ('Часовници', 'Часовници'), ('Кујнски прибор', 'Кујнски прибор'), ('Декоративни работи', 'Декоративни работи'), ('Интериор', 'Интериор'), ('Музички инструменти', 'Музички инструменти'), ('Играчки', 'Играчки'), ('Текстил', 'Текстил')], max_length=255),
        ),
    ]
